#!/usr/bin/env python3
"""Generate all simulation inputs and a Makefile for a simple WCSS.

Usage:
    python 00_generate.py --n 10
    python 00_generate.py --n 100 --master-seed 12345
"""

import argparse
import os
import subprocess
import sys
from datetime import date, timedelta

import numpy as np


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

NUM_TIPS = 200
NUM_SITES = 30000
MU = 1e-3
CONST_POP_N0 = 1.0
T0 = "2026-01-01"
TIP_DATE_START = date(2025, 1, 1)
TIP_DATE_END = date(2025, 12, 31)

# Delphy's hardcoded kappa prior: log(kappa) ~ Normal(mean=1.0, std=1.25)
KAPPA_MEAN_LOG = 1.0
KAPPA_SIGMA_LOG = 1.25

# Delphy run parameters
STEPS = 20_000_000
LOG_EVERY = 20_000
TREE_EVERY = 20_000

# Fixed seed for tip date generation (reproducibility)
TIP_SEED = 42

# Default master seed for replicate parameter sampling
DEFAULT_MASTER_SEED = 2025

# Path to binaries (relative to the 02_simple directory)
SAPLING_REL = "../../sapling"
DELPHY_REL = "../../delphy"


# ---------------------------------------------------------------------------
# Step 1: Generate tips file
# ---------------------------------------------------------------------------

def generate_tips_file(out_path):
    """Write tips.txt with 200 tips, dates uniform over 2025."""
    rng = np.random.default_rng(TIP_SEED)
    num_days = (TIP_DATE_END - TIP_DATE_START).days  # 364
    day_offsets = rng.integers(0, num_days + 1, size=NUM_TIPS)

    with open(out_path, "w") as f:
        for i in range(NUM_TIPS):
            tip_date = TIP_DATE_START + timedelta(days=int(day_offsets[i]))
            f.write(f"TIP_{i:03d}|{tip_date.isoformat()}\n")

    print(f"Wrote {out_path} ({NUM_TIPS} tips)")


# ---------------------------------------------------------------------------
# Step 2: Run Sapling for each replicate
# ---------------------------------------------------------------------------

def sample_prior_params(rng):
    """Sample kappa and pi from their priors."""
    pi = rng.dirichlet([1.0, 1.0, 1.0, 1.0])
    log_kappa = rng.normal(KAPPA_MEAN_LOG, KAPPA_SIGMA_LOG)
    kappa = np.exp(log_kappa)
    return kappa, pi


def run_sapling(i, kappa, pi, replicate_seed, tips_file, script_dir):
    """Run Sapling to simulate data for replicate i."""
    sim_dir = os.path.join(script_dir, f"sim_{i:03d}")
    os.makedirs(sim_dir, exist_ok=True)

    prefix = f"sim_{i:03d}"
    cmd = [
        os.path.join(script_dir, SAPLING_REL),
        "--tip-file", tips_file,
        "--t0", T0,
        "--const-pop-n0", str(CONST_POP_N0),
        "--mu", str(MU),
        "--hky-kappa", str(kappa),
        "--hky-pi-A", str(pi[0]),
        "--hky-pi-C", str(pi[1]),
        "--hky-pi-G", str(pi[2]),
        "--hky-pi-T", str(pi[3]),
        "--num-sites", str(NUM_SITES),
        "--seed", str(replicate_seed),
        "--out-maple", os.path.join(sim_dir, f"{prefix}.maple"),
        "--out-info", os.path.join(sim_dir, f"{prefix}_info.json"),
        "--out-newick", os.path.join(sim_dir, f"{prefix}.nwk"),
        "--out-nexus", os.path.join(sim_dir, f"{prefix}.nexus"),
        "--out-fasta", os.path.join(sim_dir, f"{prefix}.fasta"),
    ]

    print(f"  Replicate {i:03d}: kappa={kappa:.4f}, "
          f"pi=({pi[0]:.4f}, {pi[1]:.4f}, {pi[2]:.4f}, {pi[3]:.4f})")
    subprocess.run(cmd, check=True)


# ---------------------------------------------------------------------------
# Step 3: Generate Makefile
# ---------------------------------------------------------------------------

def generate_makefile(n, script_dir):
    """Generate a Makefile to drive all Delphy runs."""
    makefile_path = os.path.join(script_dir, "Makefile")

    # Build the list of targets explicitly (pattern rules can't use $* in prerequisites
    # for files like sim_000/sim_000.maple where the stem appears twice)
    lines = []
    lines.append("# Auto-generated by 00_generate.py — do not edit")
    lines.append(f"DELPHY = {DELPHY_REL}")
    lines.append("")

    all_targets = " ".join(f"sim_{i:03d}/.done" for i in range(n))
    lines.append(f"all: {all_targets}")
    lines.append("")

    for i in range(n):
        tag = f"{i:03d}"
        lines.append(f"sim_{tag}/.done: sim_{tag}/sim_{tag}.maple")
        lines.append(f"\t$(DELPHY) \\")
        lines.append(f"\t  --v0-in-maple $< \\")
        lines.append(f"\t  --v0-steps {STEPS} \\")
        lines.append(f"\t  --v0-out-log-file sim_{tag}/delphy_{tag}.log \\")
        lines.append(f"\t  --v0-log-every {LOG_EVERY} \\")
        lines.append(f"\t  --v0-out-trees-file sim_{tag}/delphy_{tag}.trees \\")
        lines.append(f"\t  --v0-tree-every {TREE_EVERY} \\")
        lines.append(f"\t  --v0-out-delphy-file sim_{tag}/delphy_{tag}.dphy \\")
        lines.append(f"\t  --v0-delphy-snapshot-every {TREE_EVERY} \\")
        lines.append(f"\t  --v0-init-mutation-rate {MU} \\")
        lines.append(f"\t  --v0-fix-mutation-rate \\")
        lines.append(f"\t  --v0-init-final-pop-size {CONST_POP_N0} \\")
        lines.append(f"\t  --v0-fix-final-pop-size \\")
        lines.append(f"\t  --v0-init-pop-growth-rate 0.0 \\")
        lines.append(f"\t  --v0-fix-pop-growth-rate \\")
        lines.append(f"\t&& touch $@")
        lines.append("")

    lines.append("clean:")
    lines.append("\trm -f sim_*/delphy_* sim_*/.done")
    lines.append("")

    lines.append(".PHONY: all clean")
    lines.append("")

    with open(makefile_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {makefile_path} ({n} replicate targets)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate WCSS simulation inputs and Makefile")
    parser.add_argument("--n", type=int, default=10,
                        help="Number of simulation replicates (default: 10)")
    parser.add_argument("--master-seed", type=int, default=DEFAULT_MASTER_SEED,
                        help=f"Master seed for parameter sampling (default: {DEFAULT_MASTER_SEED})")
    args = parser.parse_args()

    n = args.n
    master_seed = args.master_seed

    # All paths relative to this script's directory
    script_dir = os.path.dirname(os.path.abspath(__file__))

    print(f"Generating WCSS with {n} replicates (master seed: {master_seed})")
    print()

    # Step 1: tips file
    tips_file = os.path.join(script_dir, "tips.txt")
    generate_tips_file(tips_file)
    print()

    # Step 2: simulate each replicate
    print("Running Sapling simulations:")
    for i in range(n):
        rng = np.random.default_rng(master_seed + i)
        kappa, pi = sample_prior_params(rng)
        replicate_seed = int(rng.integers(0, 2**31))
        run_sapling(i, kappa, pi, replicate_seed, tips_file, script_dir)
    print()

    # Step 3: Makefile
    generate_makefile(n, script_dir)
    print()

    print("Done!  Next steps:")
    print(f"  cd {os.path.relpath(script_dir)}")
    print(f"  make -j4   # run Delphy on all {n} replicates")


if __name__ == "__main__":
    main()
